In [1]:
import numpy as np
x1 = [1,2,3]
x2 = [4,5,6]
x1+x2

[1, 2, 3, 4, 5, 6]

In [4]:
a1 = np.array(x1)
a2 = np.array(x2)
a1+a2, a1-a2, a1*a2, a1/a2, a1**a2

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([0, 0, 0]),
 array([  1,  32, 729]))

In [5]:
a3 = np.array([3,4,5])
a4 = np.array([4,4,4])
a3<a4

array([ True, False, False])

In [7]:
a5=np.array([[1,2],[3,4]])
a6 = np.array([[5,6],[7,8]])
a5*a6

array([[ 5, 12],
       [21, 32]])

In [10]:
a5.dot(a6)

array([[19, 22],
       [43, 50]])

In [15]:
a6 = a5
print hex(id(a5)), hex(id(a6))
a7 = a5.copy()
print hex(id(a7)), hex(id(a5))

0x10b848a0L 0x10b848a0L
0x10b96210L 0x10b848a0L


In [18]:
a8 = np.array([1,2,3,4,5,6])
print a8.mean(), a8.max(), a8.std()

 3.5 6 1.707825127659933


In [22]:
print a5
print a5.mean(), a5.mean(axis=0), a5.mean(axis=1)

[[1 2]
 [3 4]]
2.5 [2. 3.] [1.5 3.5]


In [26]:
np.median(a5), np.median(a8)

(2.5, 3.5)